# wrangler.toml
# Nome do seu projeto na Cloudflare Pages. Mude se for diferente.
name = "cronograma-ia"

# Diretório de saída do build do Next.js
pages_build_output_dir = "frontend/.next"

# Habilita a compatibilidade com APIs do Node.js para as funções do seu site.
compatibility_flags = ["nodejs_compat"]

# Define a data de compatibilidade para garantir o funcionamento estável das APIs.
compatibility_date = "2024-03-20"
