[build]
command = "cd frontend && npm install && npm run build"
pages_build_output_dir = ".vercel/output/static"

[site]
bucket = "./frontend/.vercel/output/static"

[build.upload]
format = "service-worker"

compatibility_flags = ["nodejs_compat"]