# wrangler.toml
# Nome do seu projeto na Cloudflare Pages. Mude se for diferente.
name = "cronograma-ia" 

# Habilita a compatibilidade com APIs do Node.js para as funções do seu site.
compatibility_flags = ["nodejs_compat"]

# Define a data de compatibilidade para garantir o funcionamento estável das APIs.
compatibility_date = "2024-03-20"

# Define o diretório de saída para o build do Pages.
pages_build_output_dir = ".vercel/output/static"