# wrangler.toml
# Configuração para Cloudflare Pages
name = "cronograma-ia"

# Define o diretório de saída do build do Next.js.
# A Cloudflare irá servir os arquivos desta pasta.
pages_build_output_dir = "frontend/.next"

# [DEPRECATED - Removido pois não é usado pelo Pages da forma como estava]
# As configurações de build serão feitas no dashboard da Cloudflare
# ou inferidas pelo framework (Next.js).
# compatibility_flags = ["nodejs_compat"]
# compatibility_date = "2024-03-20"
